feat: add sign-in sign-up
leokotman/taskmanager pull request #10
Opened 2022-11-16 17:12 UTC by leokotman

у меня работает только форма Sign Up.
Sign in / Log out (после регистрации) - выдают такую ошибку, я не понимаю, в чем проблема.

p.s. исходя из вывода rails routes исправил
<img width="1364" alt="Screenshot 2022-11-16 at 18 11 05" src="https://user-images.githubusercontent.com/71670937/202247428-59fdf093-0a09-48a5-a34d-019286003cf3.png">

`link_to "Sign up", new_developer_path` (в уроке) на 
<img width="1364" alt="Screenshot 2022-11-16 at 18 11 05" src="https://user-images.githubusercontent.com/71670937/202247428-59fdf093-0a09-48a5-a34d-019286003cf3.png">

`link_to "Sign up", new_developers_path`

т.к тоже выдавал путь ошибку

<img width="1512" alt="Screenshot 2022-11-16 at 18 05 37" src="https://user-images.githubusercontent.com/71670937/202246940-00353cba-c8a1-4765-ad65-18fb5bcff239.png">

2022-11-16 17:33 UTC, greybutton requested changes
типа у тебя ошибка после добавления ссылок появилась?

2022-11-16 17:37 UTC, greybutton commented
попробуй в контроллере `SessionForm` поменяь на `::SessionForm`

2022-11-16 18:03 UTC, leokotman commented
> типа у тебя ошибка после добавления ссылок появилась?

да, причем sign-up работает, а sign-in кнопка и log out (после регистрации) выдает такую ошибку.


> попробуй в контроллере `SessionForm` поменяь на `::SessionForm`

попробую

2022-11-16 18:23 UTC, leokotman commented
Менять было не нужно. после того как собрал проект заново и миграции сделал - все заработало с регистрацией, логином, логаутом. Так что все написано ок

2022-11-16 18:27 UTC, leokotman commented
<img width="1287" alt="Screenshot 2022-11-16 at 19 25 50" src="https://user-images.githubusercontent.com/71670937/202262695-7bf6ae41-d5d9-4615-a95e-a00986981277.png">

2022-11-17 06:16 UTC, greybutton requested changes
сделай тогда реквест с кодом по заданию

2022-11-17 09:21 UTC, leokotman commented
> сделай тогда реквест с кодом по заданию

да, ты прав, извини. сделал на предыдущую ветку

2022-11-17 09:25 UTC, greybutton approved these changes

2022-11-17 09:51 UTC, merged