Feature/admin users
leokotman/taskmanager pull request #11
Opened 2022-11-17 16:32 UTC by leokotman

Комментарии по коду (почему иногда делал не так как в заданиях):

1) Не создавал фабрику для админа (в [задании авторизация](https://learn.dualboot.ru/courses/5/lessons/78/practices/1173) ), т.к тесты ругались на дубликат, ну и у нас это уже было написано в фабрике юзера раньше. Соответственно и в задании рефакторинга также не добавлял sequence для фабрики
<img width="1512" alt="factory dublicate" src="https://user-images.githubusercontent.com/71670937/202501852-eb8ef47d-4420-4a8d-ba1a-f577f444873c.png">

2) В [задании Меню и текущий пользователь](https://learn.dualboot.ru/courses/5/lessons/78/practices/1178) сказано править несуществующий файл layout.html.slim (у меня это application.html.slim и в предыдущих заданиях так было). Вносил правки соот
<img width="1512" alt="Screenshot 2022-11-17 at 16 05 59" src="https://user-images.githubusercontent.com/71670937/202502811-ca64ae4d-98a1-45d1-b59d-2f3d27cbbe94.png">
ветственно в application.html.slim.

Финальный результат админки после сидов и проверки функциональности (все тесты проходят):
<img width="1192" alt="Screenshot 2022-11-17 at 17 24 25" src="https://user-images.githubusercontent.com/71670937/202503076-11dbd094-0757-47f1-be41-d1ced1d0e651.png">

2022-11-17 18:33 UTC, greybutton requested changes

2022-11-17 18:33 UTC, greybutton commented on app/views/admin/users/edit.html.slim
> +  = render partial: 'form', locals: { f: f }
форма немного разорванной получается, можно весь симпл форм убрать в _form и прокидывать из edit/new нужный url

2022-11-17 18:46 UTC, leokotman commented on app/views/admin/users/edit.html.slim
> +  = render partial: 'form', locals: { f: f }
Отличное замечание, мне не очень было понятно как сделать - и спасибо за намек прокинуть лучше путь. Исправил

2022-11-18 05:24 UTC, greybutton approved these changes

2022-11-18 10:40 UTC, merged