Feature/api
leokotman/taskmanager pull request #12
Opened 2022-11-18 14:04 UTC by leokotman

Если писать `respond_with(task, serializer: TaskSerializer)` в tasks_controller.rb  как в уроке (без : перед TaskSerializer) - то у меня такая ошибка uninitialized constant:
<img width="1512" alt="Screenshot 2022-11-18 at 13 59 22" src="https://user-images.githubusercontent.com/71670937/202722284-97d49843-2719-43d1-a5ff-e9be674eca81.png">

а если я пишу :TaskSerializer,  то другая (я думал это решит проблему, но вылезла еще ошибка с undefined method 'new'):
<img width="1512" alt="Screenshot 2022-11-18 at 13 57 47" src="https://user-images.githubusercontent.com/71670937/202722660-f8a47b1e-2ec7-4992-926e-8e75a7dbd87e.png">

не понял, что я делаю не так.

2022-11-18 14:38 UTC, greybutton requested changes

2022-11-18 14:38 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +  # POST /api/v1/tasks/:id
не правильный урл для пост

2022-11-18 14:38 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    respond_with(tasks, each_serializer: :TaskSerializer, root: 'items', meta: build_meta(tasks))
файл сериалайзера называется во множественном числе, в этом ошибка

2022-11-18 14:47 UTC, leokotman commented on app/controllers/api/v1/tasks_controller.rb
> +    respond_with(tasks, each_serializer: :TaskSerializer, root: 'items', meta: build_meta(tasks))
Ох, понятно, спасибо большое!!!

2022-11-18 14:54 UTC, leokotman commented on app/controllers/api/v1/tasks_controller.rb
> +  # POST /api/v1/tasks/:id
вижу в rails routes, что у меня и GET tasks другой урл
я брал из урока, это в уроке ошибка или мне нужно было свой вставлять?
<img width="1512" alt="Screenshot 2022-11-18 at 15 52 26" src="https://user-images.githubusercontent.com/71670937/202733128-22f5d2ba-3949-4b9f-9b68-a75e671f0b7c.png">

2022-11-18 17:47 UTC, leokotman commented
Разобрался с ошибками:
1) исправил state + expired_at в task factory
2) expired_at в tasks_controller

<img width="1436" alt="Screenshot 2022-11-18 at 18 40 29" src="https://user-images.githubusercontent.com/71670937/202768959-0fc8a8df-1549-4ed9-9dc4-82fc95209d8e.png">

2022-11-18 18:03 UTC, leokotman commented
Вопрос: так и должно быть? Что не так с методом respond_with?

В браузере мне не отображаются таски, выдает такую ошибку:
<img width="1254" alt="Screenshot 2022-11-18 at 19 00 23" src="https://user-images.githubusercontent.com/71670937/202772162-3c2bf340-4869-47f1-bfb1-d0e86ee3c03c.png">

Когда же я исправил код на [предложенный здесь](https://stackoverflow.com/questions/36323525/actioncontrollerunknownformat-in-rails-as-api-show-action), то у меня получился вывод таски которая есть в базе:

<img width="1415" alt="Screenshot 2022-11-18 at 18 59 54" src="https://user-images.githubusercontent.com/71670937/202772338-56f7ab83-7890-461d-bda4-b77b7a9e4d98.png">

2022-11-19 06:02 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +  # POST /api/v1/tasks/:id
в уроке ошибка

2022-11-19 06:03 UTC, greybutton commented
render не надо, вот это попробуй https://stackoverflow.com/questions/36323525/actioncontrollerunknownformat-in-rails-as-api-show-action#comment60270582_36323525

2022-11-21 09:39 UTC, leokotman commented
Ура, заработало! 

> render не надо, вот это попробуй https://stackoverflow.com/questions/36323525/actioncontrollerunknownformat-in-rails-as-api-show-action#comment60270582_36323525

заработало! 

<img width="1312" alt="Screenshot 2022-11-21 at 10 38 26" src="https://user-images.githubusercontent.com/71670937/203017033-606cb7a8-df6a-43e7-8786-aa890fc4d739.png">

2022-11-21 12:05 UTC, greybutton approved these changes

2022-11-21 14:32 UTC, merged