Feature/redux
leokotman/taskmanager pull request #17
Opened 2022-12-14 18:51 UTC by leokotman

Создал store, начал прописывать экшны. Борда загружается, проблема случилось с открытием карточки редактирования - никак таска не загружается в эту карточку, я не понимаю что делаю не так.

Изначально я ничего в EditPopUp не менял,

<img width="1512" alt="Screenshot 2022-12-14 at 19 09 54" src="https://user-images.githubusercontent.com/71670937/207685536-df9235d0-be93-417a-8ed4-6ceebd8c68b6.png">

Но после того как не загрузились данные в карточке - решил передавать task через пропсы из TaskBoard - все так же. причем useEffect и загрузка данных работает, но task внутри карточки не загружается все равно.

Это какой результат в последнем коммите:

<img width="1512" alt="Screenshot 2022-12-14 at 19 37 55" src="https://user-images.githubusercontent.com/71670937/207685683-0759daca-45fa-4cf7-a2ec-c7c9748313f3.png">

2022-12-15 16:06 UTC, leokotman commented
Вся функциональность реализована, всё работает

2022-12-15 17:33 UTC, greybutton requested changes

2022-12-15 17:33 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +  const [task, setTask] = useState(null);
это можно вернуть на старое место)

2022-12-15 17:33 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> -    onCardLoad(cardId).then(setTask);
это можно вернуть как было)

2022-12-15 17:33 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +    return onCardDestroy(task);
здесь ретерн наверно можно убрать, дальше же никуда цепочка не идет

2022-12-15 17:33 UTC, greybutton commented on app/javascript/containers/TaskBoard.js
> +    handleClose();
закрывать думаю лучше после создания. если в создании будут ошибки, а ты уже закрыл форму, что делать? если форма открыта, то можно в ней показать ошибки

2022-12-15 17:33 UTC, greybutton commented on app/javascript/containers/TaskBoard.js
> +    const attributes = TaskForm.attributesToSubmit(task);
здесь зачем аттрибуты?

2022-12-15 17:33 UTC, greybutton commented on app/javascript/slices/TasksSlice.js
> +      .catch((err) => {
обработку ошибок лучше делать в компоненте. лог в консоль не поможет юзеру. и какие то запросы ловишь, какие то нет. ошибка по идее в каждом может быть. убери просто катч

2022-12-16 09:14 UTC, leokotman commented on app/javascript/containers/TaskBoard.js
> +    const attributes = TaskForm.attributesToSubmit(task);
согласен что лишние, можно передать просто таск и внутри слайса брать task.id.

2022-12-16 09:22 UTC, leokotman commented on app/javascript/components/EditPopup/EditPopup.js
> +    return onCardDestroy(task);
согласен, таска не возвращается т.к удалена

2022-12-16 09:24 UTC, leokotman commented on app/javascript/containers/TaskBoard.js
> +    handleClose();
я об этом думал, подумаю как сделать после функции

2022-12-16 09:36 UTC, leokotman commented on app/javascript/slices/TasksSlice.js
> +      .catch((err) => {
согласен, перенесу обработки ошибок в taskBoard

2022-12-16 11:45 UTC, leokotman commented
[3f83f78](https://github.com/leokotman/taskmanager/pull/17/commits/3f83f7868791b25c9fd69d51526c42444485599a) Здесь реализовал сообщения об ошибке в компонентах, также закрытие модального окна после выполнения функции

2022-12-16 11:46 UTC, leokotman commented
[72244f1](https://github.com/leokotman/taskmanager/pull/17/commits/72244f1adece0583dbc0d864e738570888c9c4ee) Здесь сделал чтобы форма добавления таски не отправлялась и не закрывалась, пока не заполнены оба поля

<img width="494" alt="Screenshot 2022-12-16 at 11 40 01" src="https://user-images.githubusercontent.com/71670937/208091525-60e5e0de-fced-47aa-bc6a-6bc7cc1e7aae.png">

2022-12-16 12:45 UTC, greybutton commented
давай оставим обработку ошибок как есть в практике

2022-12-16 14:11 UTC, leokotman commented
[0d7415a](https://github.com/leokotman/taskmanager/pull/17/commits/0d7415a05bc94de9f0e5b099a9763e909d07182c) если совсем не делать return внутри функций в TaskBoard, то компоненты не смогут отловить ошибки в блоке catch - мне об этом написала ошибка

То есть когда у меня такой код
<img width="1428" alt="Screenshot 2022-12-16 at 14 58 02" src="https://user-images.githubusercontent.com/71670937/208116597-ba7c5977-617b-4030-bbfa-2dd9606dbd50.png">

То в браузере ошибка что catch блок не может примениться на undefined (при изменении карточки handleTaskUpdate)

<img width="1512" alt="Screenshot 2022-12-16 at 14 57 41" src="https://user-images.githubusercontent.com/71670937/208116505-f052746d-6e2b-48e2-809b-7d43ba49880b.png">

2022-12-16 16:37 UTC, greybutton approved these changes

2022-12-16 18:31 UTC, merged