Feature/models factory bot
leokotman/taskmanager pull request #3
Opened 2022-11-10 09:55 UTC by leokotman

Added factory bot, edits in rubocop settings & gemfile
(on base 'rails for beginners' branch)

2022-11-10 18:50 UTC, greybutton requested changes
много левого кода не из обучения

2022-11-10 18:50 UTC, greybutton commented on .eslintrc.json
> +{
зачем этот файл?

2022-11-10 18:50 UTC, greybutton commented on .vscode/settings.json
> +{
локальные настройки редактора не надо в общий проект добавлять

2022-11-10 18:50 UTC, greybutton commented on README.md
> +docker run -it -v /Users/leo_personal/Documents/develop/TaskManager:/task_manager task-manager bash
`docker-compose run web bash` так по идее тоже должно работать и короче команда

2022-11-10 18:50 UTC, greybutton commented on app/assets/stylesheets/articles.scss
> +// Place all the styles related to the Articles controller here.
этот файл зачем?

2022-11-10 18:50 UTC, greybutton commented on app/assets/stylesheets/comments.scss
> +// Place all the styles related to the Comments controller here.
и этот

2022-11-10 18:50 UTC, greybutton commented on Rakefile
> +# frozen_string_literal: true
рубокоп в контейнере запускал?

2022-11-11 16:03 UTC, leokotman commented on README.md
> +docker run -it -v /Users/leo_personal/Documents/develop/TaskManager:/task_manager task-manager bash
Да, тут я зря конечно полный путь поставил, работает короткая команда тоже

2022-11-11 16:04 UTC, leokotman commented on .eslintrc.json
> +{
Установил eslint и сделал конфигурацию, возможно преждевременно

2022-11-11 16:06 UTC, leokotman commented on Rakefile
> +# frozen_string_literal: true
Да, через докер открыл терминал контейнера и там проверял

2022-11-11 16:17 UTC, leokotman commented on app/assets/stylesheets/articles.scss
> +// Place all the styles related to the Articles controller here.
при генерации моделей файлы стилей автоматически сгенерировались
я тренировался на статье [rails для начинающих](http://rusrails.ru/getting-started) и решил оставить файлы, чтобы сверяться

2022-11-11 18:02 UTC, greybutton requested changes
удали весь код связаный с гет стартед рельс, он не нужен в проекте. хорошо что прошел, но не надо было делать это в таск менеджер. это отдельный проект

2022-11-14 16:37 UTC, greybutton approved these changes

2022-11-15 15:05 UTC, merged