Feature/models generation
leokotman/taskmanager pull request #4
Opened 2022-11-10 12:35 UTC by leokotman

2022-11-10 18:52 UTC, greybutton requested changes

2022-11-10 18:52 UTC, greybutton commented on test/factories/sequence.rb
> +    }"
почему так?

2022-11-10 18:52 UTC, greybutton commented on test/factories/sequence.rb
> +  sequence :type do |n|
на type не нужен sequence

2022-11-10 18:52 UTC, greybutton commented on test/models/task_test.rb
> +  # end
тест не дописан

2022-11-11 16:28 UTC, leokotman commented on test/factories/sequence.rb
> +    }"
В уроке так было, я что-то не так понял?
<img width="705" alt="Screenshot 2022-11-11 at 17 27 46" src="https://user-images.githubusercontent.com/71670937/201385849-aa1dfd18-26a6-445d-b113-e7534e6ae1fd.png">

2022-11-11 16:48 UTC, leokotman commented on test/models/task_test.rb
> +  # end
Дописал и всё прошло

/task_manager # rails test
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
Run options: --seed 60640

# Running:

.....

Finished in 0.302405s, 16.5341 runs/s, 16.5341 assertions/s.
5 runs, 5 assertions, 0 failures, 0 errors, 0 skips

2022-11-11 18:05 UTC, greybutton approved these changes
аппрувлю, но пока не мержи, пока с гет стартед не разберешься

2022-11-11 18:05 UTC, greybutton commented on test/factories/sequence.rb
> +    }"
нет, походу баг отображения в либе)

2022-11-15 15:14 UTC, leokotman commented
> аппрувлю, но пока не мержи, пока с гет стартед не разберешься

удалил ненужный код в [пуле №3 предыдущем](https://github.com/leokotman/taskmanager/pull/3), смержил в девелоп. теперь и эту буду мержить, т.к все исправлено.

2022-11-15 15:15 UTC, merged