Feature/associations
leokotman/taskmanager pull request #5
Opened 2022-11-10 14:28 UTC by leokotman

2022-11-10 18:55 UTC, greybutton requested changes

2022-11-10 18:55 UTC, greybutton commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
можно взять URI::MailTo::EMAIL_REGEXP из руби

2022-11-10 18:55 UTC, greybutton commented on test/factories/tasks.rb
> +    author_id { association :author, factory: :manager }
author factory: :manager

2022-11-10 18:55 UTC, greybutton commented on test/factories/tasks.rb
> +    assignee_id { association :assignee, factory: :manager }
по аналогии с автором

2022-11-11 17:04 UTC, leokotman commented on test/factories/tasks.rb
> +    author_id { association :author, factory: :manager }
я где-то прочитал, что мой вариант более расширенная версия (мне так понятнее стало), или это неверно в принципе так писать (другой смысл?)?

2022-11-11 18:08 UTC, greybutton commented on test/factories/tasks.rb
> +    author_id { association :author, factory: :manager }
в ид странно ассоциацию записывать. здесь типа работа с сущностями, либо ассоциацию писать как то по другому, либо как у нас пример через author

2022-11-11 18:08 UTC, greybutton approved these changes
аппрувлю, но надо конфликты поправить и гет стартед

2022-11-15 15:22 UTC, leokotman commented on test/factories/tasks.rb
> +    author_id { association :author, factory: :manager }
спасибо большое, сделаю так, думаю со временем станет понятнее что к чему

2022-11-15 15:27 UTC, merged