Feature/registration session
leokotman/taskmanager pull request #8
Opened 2022-11-16 16:01 UTC by leokotman

2022-11-16 17:31 UTC, greybutton requested changes
> [Merge branch 'feature/web_layout' into feature/registration-session](https://github.com/leokotman/taskmanager/pull/8/commits/65f781893368cc7b3d97f827ac6f2608896288be)

не должно быть таких коммитов

2022-11-16 18:01 UTC, leokotman commented
это я смержил ветку в которой были исправления в css require

2022-11-16 18:40 UTC, leokotman commented
Исправлено

2022-11-17 06:11 UTC, greybutton approved these changes

2022-11-17 09:49 UTC, merged